version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: McpServer/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Elasticsearch__Url=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - mcp-net

  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - mcp-net

volumes:
  esdata:
    driver: local

networks:
  mcp-net:
    driver: bridge
