version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: McpServer/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - Elasticsearch__Url=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - mcp-net

  elasticsearch:
    image: elasticsearch:9.0.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - mcp-net

volumes:
  esdata:
    driver: local

networks:
  mcp-net:
    driver: bridge
